// Every visible text, in German and English. German is the default.
// Entries are strings with {placeholders}, or functions for plurals.

const num = (lang, n) => (lang === 'de' ? String(n).replace('.', ',') : String(n));

// "3 semitones (1.5 tones)" / "3 Halbtöne (1,5 Ganztöne)"
const enSemis = (n) => `${n} semitone${n === 1 ? '' : 's'} (${n === 2 ? '1 tone' : `${num('en', n / 2)} tones`})`;
const deSemis = (n) => `${n} ${n === 1 ? 'Halbton' : 'Halbtöne'} (${num('de', n / 2)} ${n === 2 ? 'Ganzton' : 'Ganztöne'})`;

export const STRINGS = {
  en: {
    // --- zone words
    'zone.semis': ({ n }) => enSemis(n),
    'zone.tones': ({ n }) => (n === 2 ? '1 tone' : `${num('en', n / 2)} tones`),
    'zone.noPitch': 'No pitch heard',
    'zone.onTarget': 'On target {t}',
    'zone.onTargetShort': 'On target',
    'zone.above': 'above',
    'zone.below': 'below',
    'zone.aboveShort': 'above',
    'zone.belowShort': 'below',
    'zone.moreThan': 'More than {n} semitones {side} {t}',
    'zone.moreThanShort': 'More than {n} semitones {side}',
    'zone.sideN': '{n} {side}',
    'zone.sideOnTarget': 'on target',
    'zone.sideNoPitch': 'no pitch',
    'zone.liveBig': ({ n, sign }) => `${sign}${n} semitone${n === 1 ? '' : 's'}`,
    'zone.liveMore': 'More than {n}',
    'zone.liveMoreSub': 'semitones {side} {t}',

    // --- values and comparisons
    'v.pitch': 'Average pitch',
    'v.spread': 'Pitch spread',
    'v.spreadValue': ({ x }) => `${x} semitones`,
    'v.range': 'Range (5–95%)',
    'v.speaking': 'Time speaking',
    'v.of': '{a} of {b}',
    'v.volume': 'Average volume',
    'v.loudest': 'Loudest',
    'v.onTarget': 'Time on {t}',
    'v.onTargetValue': '{p}% of speaking time',
    'v.onTargetShort': '{p}%',
    'v.target': 'target',
    'change.same': 'Same distance to {t} as the Before session.',
    'change.closer': '{d} closer to {t} than the Before session.',
    'change.further': '{d} further from {t} than the Before session.',
    'cmp.same': 'same distance',
    'cmp.closer': '{d} closer',
    'cmp.further': '{d} further',
    'vol.same': 'same volume',
    'vol.louder': '{n} dB louder',
    'vol.quieter': '{n} dB quieter',
    'since.closer': 'Since first day: {d} closer to {t}',
    'since.further': 'Since first day: {d} further from {t}',
    'since.same': 'Since first day: same distance to {t}',
    'name.before': 'Before session',
    'name.after': 'After session',
    'name.recording': 'Recording {n}',

    // --- common
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.continue': 'Continue',

    // --- Patients
    'patients.pageTitle': 'Patients · FZero',
    'patients.title': 'Patients',
    'patients.add': 'Add patient',
    'patients.empty': 'No patients yet',
    'patients.emptyHint': 'Add your first patient to start.',
    'patients.footnote': 'Data stays on this device.',
    'legal.privacy': 'Privacy',
    'legal.imprint': 'Imprint',
    'patients.practice': 'Practice settings',
    'patients.safety': 'Finish the safety checklist before using FZero with patients.',
    'patients.safetyOpen': 'Open checklist',
    'card.noRecordings': 'No recordings yet',
    'card.lastSession': 'Last session {d}, ended:',
    'card.firstDay': 'First day · target {t}',
    'card.unnamed': 'Unnamed patient',
    'add.title': 'New patient',
    'add.first': 'First name',
    'add.last': 'Last name',
    'add.consent': 'Signed consent for voice recordings is on file',
    'add.consentHint': 'You can also tick this later in the Profile. The form is under Practice → Documents.',
    'add.hint': "Year of birth, voice and calibration come next, in the patient's Profile.",

    // --- patient page
    'nav.patients': '‹ Patients',
    'tab.measure': 'Measure',
    'tab.history': 'History',
    'tab.profile': 'Profile',
    'title.history': '{name} · History',
    'title.profile': 'Profile',
    'patient.fallback': 'Patient',
    'confirm.deletePatient': 'Delete {name} and all their recordings? This cannot be undone.',

    // --- Measure
    'setup.title': "Before {name}'s first recording",
    'setup.titleNoName': 'Before the first recording',
    'setup.consent': 'Consent on file',
    'setup.details': 'Add details',
    'setup.target': 'Target note set',
    'setup.calibrated': 'Voice calibrated',
    'setup.openProfile': 'Open Profile',
    'setup.calibrate': 'Calibrate',
    'm.ready': 'Ready',
    'm.listening': 'Listening',
    'm.recording': 'Recording {time}',
    'm.start': 'Start',
    'm.stop': 'Stop',
    'm.saving': 'Saving…',
    'm.voiceOn': 'Voice on {note}',
    'm.heard': '✓ Hearing the patient',
    'm.silent': "Can't hear a voice yet. Ask the patient to say something, about 30 cm from the device.",
    'm.micOff': 'The microphone turns on when you press Start.',
    'm.nextBefore': 'Next: Before session',
    'm.nextAfter': 'Next: After session',
    'm.today': 'Today',
    'm.noTakes': 'No recordings yet',
    'm.undo': 'Undo',
    'm.saved': '{name} saved ·',
    'm.discarded': '{name} discarded ·',
    'm.micHelp': 'FZero could not use the microphone. In {browser}:',
    'm.audioFailed': 'Audio could not be recorded, so only the numbers will be saved.',
    'm.nothing': 'Nothing was heard, so nothing was saved. Check the microphone and try again.',
    'm.tooShort': 'Too short to save ({time}). Try again.',
    'm.audioFull': "Audio couldn't be saved: storage is full.",
    'm.audioError': "Audio couldn't be saved.",
    'm.saveFull': "This take couldn't be saved: the device storage is full.",
    'r.savedToday': 'Saved · today {time}',
    'r.nextAfter': 'The next recording today becomes the After session.',
    'r.done': 'Done',
    'r.discard': 'Discard take',
    'r.summaryHead': '{patient} · today {time} · {name}',
    'r.before': 'Before',
    'r.after': 'After',
    'r.showAll': 'Show all 7 values ›',
    'r.showFewer': 'Show fewer',
    'r.onTargetNote': 'Time on {t} = share of speaking time within ½ semitone of {t}.',
    'r.another': 'Record another',

    // --- calibration
    'cal.warning':
      "Recalibrating now changes how volume is measured. Today's volume before and after won't compare directly. Pitch is not affected.\n\nCalibrate anyway?",
    'cal.title': "Calibrate {name}'s voice",
    'cal.text': 'Ask {name} to talk normally for 5 seconds. Keep the device about 30 cm away, the same distance every time.',
    'cal.thePatient': 'the patient',
    'cal.listen': 'Start listening',
    'cal.waiting': 'Waiting for the microphone…',
    'cal.blocked': 'The microphone is blocked. Allow it in Settings, then try again.',
    'cal.retry': 'Try again',
    'cal.listening': 'Listening…',
    'cal.nothing': 'Nothing came through. Check the microphone and try again.',
    'cal.saved': 'Saved',

    // --- History
    'h.todayEnded': 'Today ended',
    'h.dayEnded': '{d} ended',
    'h.today': 'Today',
    'h.oneRec': 'one recording, {s}',
    'h.startedEnded': 'started {a}, ended {b}',
    'h.vs': 'vs {d}',
    'h.firstSession': ' (first session)',
    'h.distNote': 'Distances in semitones from {t}.',
    'h.different': 'Different calibration. Compare volume with care.',
    'h.changed': 'Calibration changed during this day. Compare volume with care.',
    'h.todayTitle': 'Today, {d}',
    'h.yesterdayTitle': 'Yesterday, {d}',
    'h.share': 'Share day',
    'h.preparing': 'Preparing…',
    'h.tapAgain': 'Tap again to share',
    'h.loadMore': 'Load more',
    'h.empty': 'No recordings yet',
    'h.emptyHint': 'Recordings appear here, grouped by day.',
    'h.details': 'Show details of {name}',
    'h.name': 'Name',
    'h.delete': 'Delete recording',
    'h.loadingAudio': 'Loading audio…',
    'h.audioGone': 'Audio no longer on this device.',
    'h.audioError': 'Audio could not be loaded.',
    'h.noAudio': 'Recorded without audio.',
    'h.confirmDelete': 'Delete “{name}” ({time})? This cannot be undone.',
    'share.title': "Share {name}'s recordings?",
    'share.text':
      "These are health data. Share them only with the patient's agreement, and only via AirDrop, Files or encrypted email, not WhatsApp or normal email.",

    // --- Profile
    'p.busy': 'Stop the recording to edit the profile.',
    'p.voice': 'Voice',
    'p.fundamental': 'Fundamental tone',
    'p.low': 'Lowest note',
    'p.high': 'Highest note',
    'p.target': 'Target note',
    'p.personal': 'Personal',
    'p.first': 'First name',
    'p.last': 'Last name',
    'p.year': 'Year of birth',
    'p.sex': 'Sex',
    'p.required': 'Required',
    'p.automatic': 'Automatic',
    'p.setRange': 'Set range',
    'sex.Female': 'Female',
    'sex.Male': 'Male',
    'sex.Intersex': 'Intersex',
    'sex.Prefer not to say': 'Prefer not to say',
    'p.outside': 'Fundamental tone is outside the range. Pick a target.',
    'p.byHand': 'Target picked by hand. Choose “Automatic” to follow the fundamental tone again.',
    'p.follows': 'The target follows the fundamental tone until you pick one.',
    'p.calibration': 'Calibration',
    'p.calibrated': 'Calibrated {d}',
    'p.notCalibrated': 'Not calibrated yet',
    'p.distance': 'Same distance every time, about 30 cm',
    'p.calibrate': 'Calibrate',
    'p.recalibrate': 'Recalibrate',
    'p.consent': 'Consent',
    'p.consentOn': 'Signed consent on file since {d}',
    'p.consentMissing': 'No signed consent on file yet',
    'p.consentMark': 'Mark as on file',
    'p.consentWithdraw': 'Withdraw',
    'p.consentHint': 'Recording needs the signed consent form. Print it from Practice → Documents.',
    'p.confirmWithdraw':
      'Withdraw consent for {name}? All recordings of {name} are deleted from this device, and recording is blocked until new consent is on file.',
    'p.deleteLink': 'Delete recordings or patient…',
    'p.deleteTitle': 'Delete',
    'p.deleteAll': 'Delete all recordings',
    'p.deletePatient': 'Delete patient',
    'p.confirmDeleteAll': ({ n, name }) => `Delete all ${n} recording${n === 1 ? '' : 's'} of ${name}? This cannot be undone.`,

    // --- Practice
    'pr.pageTitle': 'Practice · FZero',
    'pr.signed': 'Patients have signed all necessary documents',
    'pr.signedHint': 'For every patient you record: signed consent form, and the patient information handed over. Then tick “Consent on file” in their Profile.',
    'pr.title': 'Practice',
    'pr.language': 'Language',
    'pr.safety': 'Safety checklist',
    'pr.safetyHint': 'Before using FZero with patients.',
    'pr.passcode': 'This iPad has a passcode',
    'pr.passcodeHint': "Settings → Face ID & Passcode (or Touch ID & Passcode). FZero can't check this, so please confirm it.",
    'pr.confirm': 'Confirm',
    'pr.confirmed': 'Confirmed',
    'pr.homescreen': 'FZero is on the Home Screen',
    'pr.homescreenHint':
      'In Safari: Share → Add to Home Screen, then open FZero from there. Otherwise Safari may delete the data after 7 days without use.',
    'pr.homescreenOk': 'Opened from the Home Screen',
    'pr.local': 'Patient data stays on this iPad',
    'pr.localHint':
      'Nothing is sent to FZero or anyone else. Opening FZero in another browser or on another device shows no patients.',
    'pr.documents': 'Documents',
    'pr.docConsent': 'Consent form for patients (to print)',
    'pr.docInfo': 'Patient information on data protection (to print)',
    'pr.docPrivacy': 'Privacy policy of this website',
    'pr.docImprint': 'Imprint',
    'pr.draft': 'Drafts: have them checked by your data protection officer before use.',
  },

  de: {
    'zone.semis': ({ n }) => deSemis(n),
    'zone.tones': ({ n }) => `${num('de', n / 2)} ${n === 2 ? 'Ganzton' : 'Ganztöne'}`,
    'zone.noPitch': 'Keine Tonhöhe erkannt',
    'zone.onTarget': 'Auf dem Zielton {t}',
    'zone.onTargetShort': 'Auf dem Zielton',
    'zone.above': 'über',
    'zone.below': 'unter',
    'zone.aboveShort': 'darüber',
    'zone.belowShort': 'darunter',
    'zone.moreThan': 'Mehr als {n} Halbtöne {side} {t}',
    'zone.moreThanShort': 'Mehr als {n} Halbtöne {side}',
    'zone.sideN': '{n} {side}',
    'zone.sideOnTarget': 'auf dem Zielton',
    'zone.sideNoPitch': 'keine Tonhöhe',
    'zone.liveBig': ({ n, sign }) => `${sign}${n} ${n === 1 ? 'Halbton' : 'Halbtöne'}`,
    'zone.liveMore': 'Mehr als {n}',
    'zone.liveMoreSub': 'Halbtöne {side} {t}',

    'v.pitch': 'Mittlere Tonhöhe',
    'v.spread': 'Tonhöhen-Streuung',
    'v.spreadValue': ({ x }) => `${x} Halbtöne`,
    'v.range': 'Umfang (5–95 %)',
    'v.speaking': 'Sprechzeit',
    'v.of': '{a} von {b}',
    'v.volume': 'Mittlere Lautstärke',
    'v.loudest': 'Maximale Lautstärke',
    'v.onTarget': 'Zeit auf {t}',
    'v.onTargetValue': '{p} % der Sprechzeit',
    'v.onTargetShort': '{p} %',
    'v.target': 'Zielton',
    'change.same': 'Gleicher Abstand zu {t} wie bei der Vorher-Aufnahme.',
    'change.closer': '{d} näher an {t} als bei der Vorher-Aufnahme.',
    'change.further': '{d} weiter weg von {t} als bei der Vorher-Aufnahme.',
    'cmp.same': 'gleicher Abstand',
    'cmp.closer': '{d} näher',
    'cmp.further': '{d} weiter weg',
    'vol.same': 'gleiche Lautstärke',
    'vol.louder': '{n} dB lauter',
    'vol.quieter': '{n} dB leiser',
    'since.closer': 'Seit dem ersten Tag: {d} näher an {t}',
    'since.further': 'Seit dem ersten Tag: {d} weiter weg von {t}',
    'since.same': 'Seit dem ersten Tag: gleicher Abstand zu {t}',
    'name.before': 'Vorher-Aufnahme',
    'name.after': 'Nachher-Aufnahme',
    'name.recording': 'Aufnahme {n}',

    'common.cancel': 'Abbrechen',
    'common.close': 'Schließen',
    'common.continue': 'Weiter',

    'patients.pageTitle': 'Patienten · FZero',
    'patients.title': 'Patienten',
    'patients.add': 'Patient hinzufügen',
    'patients.empty': 'Noch keine Patienten',
    'patients.emptyHint': 'Fügen Sie Ihren ersten Patienten hinzu.',
    'patients.footnote': 'Die Daten bleiben auf diesem Gerät.',
    'legal.privacy': 'Datenschutz',
    'legal.imprint': 'Impressum',
    'patients.practice': 'Praxis-Einstellungen',
    'patients.safety': 'Schließen Sie die Sicherheits-Checkliste ab, bevor Sie FZero mit Patienten nutzen.',
    'patients.safetyOpen': 'Checkliste öffnen',
    'card.noRecordings': 'Noch keine Aufnahmen',
    'card.lastSession': 'Letzte Sitzung {d}, Ende:',
    'card.firstDay': 'Erster Tag · Zielton {t}',
    'card.unnamed': 'Patient ohne Namen',
    'add.title': 'Neuer Patient',
    'add.first': 'Vorname',
    'add.last': 'Nachname',
    'add.consent': 'Unterschriebene Einwilligung zu Sprachaufnahmen liegt vor',
    'add.consentHint': 'Sie können das auch später im Profil abhaken. Das Formular finden Sie unter Praxis → Dokumente.',
    'add.hint': 'Geburtsjahr, Stimme und Kalibrierung folgen im Profil des Patienten.',

    'nav.patients': '‹ Patienten',
    'tab.measure': 'Messen',
    'tab.history': 'Verlauf',
    'tab.profile': 'Profil',
    'title.history': '{name} · Verlauf',
    'title.profile': 'Profil',
    'patient.fallback': 'Patient',
    'confirm.deletePatient': '{name} und alle Aufnahmen löschen? Das lässt sich nicht rückgängig machen.',

    'setup.title': 'Vor der ersten Aufnahme von {name}',
    'setup.titleNoName': 'Vor der ersten Aufnahme',
    'setup.consent': 'Einwilligung liegt vor',
    'setup.details': 'Angaben ergänzen',
    'setup.target': 'Zielton festgelegt',
    'setup.calibrated': 'Stimme kalibriert',
    'setup.openProfile': 'Profil öffnen',
    'setup.calibrate': 'Kalibrieren',
    'm.ready': 'Bereit',
    'm.listening': 'Hört zu',
    'm.recording': 'Aufnahme {time}',
    'm.start': 'Start',
    'm.stop': 'Stopp',
    'm.saving': 'Speichert…',
    'm.voiceOn': 'Stimme auf {note}',
    'm.heard': '✓ Die Stimme ist zu hören',
    'm.silent': 'Noch keine Stimme zu hören. Bitten Sie den Patienten, etwas zu sagen, etwa 30 cm vom Gerät entfernt.',
    'm.micOff': 'Das Mikrofon schaltet sich ein, wenn Sie auf Start tippen.',
    'm.nextBefore': 'Als Nächstes: Vorher-Aufnahme',
    'm.nextAfter': 'Als Nächstes: Nachher-Aufnahme',
    'm.today': 'Heute',
    'm.noTakes': 'Noch keine Aufnahmen',
    'm.undo': 'Rückgängig',
    'm.saved': '{name} gespeichert ·',
    'm.discarded': '{name} verworfen ·',
    'm.micHelp': 'FZero konnte das Mikrofon nicht nutzen. In {browser}:',
    'm.audioFailed': 'Ton konnte nicht aufgenommen werden; nur die Messwerte werden gespeichert.',
    'm.nothing': 'Es war nichts zu hören, daher wurde nichts gespeichert. Prüfen Sie das Mikrofon und versuchen Sie es erneut.',
    'm.tooShort': 'Zu kurz zum Speichern ({time}). Bitte erneut versuchen.',
    'm.audioFull': 'Ton konnte nicht gespeichert werden: Speicher voll.',
    'm.audioError': 'Ton konnte nicht gespeichert werden.',
    'm.saveFull': 'Diese Aufnahme konnte nicht gespeichert werden: Gerätespeicher voll.',
    'r.savedToday': 'Gespeichert · heute {time}',
    'r.nextAfter': 'Die nächste Aufnahme heute wird die Nachher-Aufnahme.',
    'r.done': 'Fertig',
    'r.discard': 'Aufnahme verwerfen',
    'r.summaryHead': '{patient} · heute {time} · {name}',
    'r.before': 'Vorher',
    'r.after': 'Nachher',
    'r.showAll': 'Alle 7 Werte zeigen ›',
    'r.showFewer': 'Weniger zeigen',
    'r.onTargetNote': 'Zeit auf {t} = Anteil der Sprechzeit innerhalb von ½ Halbton um {t}.',
    'r.another': 'Weitere Aufnahme',

    'cal.warning':
      'Eine neue Kalibrierung ändert, wie die Lautstärke gemessen wird. Die heutige Lautstärke vorher und nachher ist dann nicht direkt vergleichbar. Die Tonhöhe ist nicht betroffen.\n\nTrotzdem kalibrieren?',
    'cal.title': 'Stimme von {name} kalibrieren',
    'cal.text': 'Bitten Sie {name}, 5 Sekunden lang normal zu sprechen. Halten Sie das Gerät etwa 30 cm entfernt, jedes Mal im gleichen Abstand.',
    'cal.thePatient': 'den Patienten',
    'cal.listen': 'Zuhören starten',
    'cal.waiting': 'Warte auf das Mikrofon…',
    'cal.blocked': 'Das Mikrofon ist blockiert. Erlauben Sie es in den Einstellungen und versuchen Sie es erneut.',
    'cal.retry': 'Erneut versuchen',
    'cal.listening': 'Hört zu…',
    'cal.nothing': 'Es kam nichts an. Prüfen Sie das Mikrofon und versuchen Sie es erneut.',
    'cal.saved': 'Gespeichert',

    'h.todayEnded': 'Heute zuletzt',
    'h.dayEnded': '{d} zuletzt',
    'h.today': 'Heute',
    'h.oneRec': 'eine Aufnahme, {s}',
    'h.startedEnded': 'Beginn {a}, Ende {b}',
    'h.vs': 'ggü. {d}',
    'h.firstSession': ' (erste Sitzung)',
    'h.distNote': 'Abstände in Halbtönen zu {t}.',
    'h.different': 'Andere Kalibrierung. Lautstärke nur vorsichtig vergleichen.',
    'h.changed': 'Die Kalibrierung hat sich an diesem Tag geändert. Lautstärke nur vorsichtig vergleichen.',
    'h.todayTitle': 'Heute, {d}',
    'h.yesterdayTitle': 'Gestern, {d}',
    'h.share': 'Tag teilen',
    'h.preparing': 'Wird vorbereitet…',
    'h.tapAgain': 'Zum Teilen erneut tippen',
    'h.loadMore': 'Mehr laden',
    'h.empty': 'Noch keine Aufnahmen',
    'h.emptyHint': 'Aufnahmen erscheinen hier, nach Tagen sortiert.',
    'h.details': 'Details zu {name} anzeigen',
    'h.name': 'Name',
    'h.delete': 'Aufnahme löschen',
    'h.loadingAudio': 'Ton wird geladen…',
    'h.audioGone': 'Der Ton ist nicht mehr auf diesem Gerät.',
    'h.audioError': 'Der Ton konnte nicht geladen werden.',
    'h.noAudio': 'Ohne Ton aufgenommen.',
    'h.confirmDelete': '„{name}“ ({time}) löschen? Das lässt sich nicht rückgängig machen.',
    'share.title': 'Aufnahmen von {name} teilen?',
    'share.text':
      'Das sind Gesundheitsdaten. Teilen Sie sie nur mit Zustimmung des Patienten und nur per AirDrop, Dateien oder verschlüsselter E-Mail, nicht per WhatsApp oder normaler E-Mail.',

    'p.busy': 'Beenden Sie die Aufnahme, um das Profil zu bearbeiten.',
    'p.voice': 'Stimme',
    'p.fundamental': 'Grundton',
    'p.low': 'Tiefster Ton',
    'p.high': 'Höchster Ton',
    'p.target': 'Zielton',
    'p.personal': 'Persönliches',
    'p.first': 'Vorname',
    'p.last': 'Nachname',
    'p.year': 'Geburtsjahr',
    'p.sex': 'Geschlecht',
    'p.required': 'Pflichtfeld',
    'p.automatic': 'Automatisch',
    'p.setRange': 'Bereich festlegen',
    'sex.Female': 'Weiblich',
    'sex.Male': 'Männlich',
    'sex.Intersex': 'Divers',
    'sex.Prefer not to say': 'Keine Angabe',
    'p.outside': 'Der Grundton liegt außerhalb des Bereichs. Bitte einen Zielton wählen.',
    'p.byHand': 'Zielton von Hand gewählt. Wählen Sie „Automatisch“, damit er wieder dem Grundton folgt.',
    'p.follows': 'Der Zielton folgt dem Grundton, bis Sie einen wählen.',
    'p.calibration': 'Kalibrierung',
    'p.calibrated': 'Kalibriert am {d}',
    'p.notCalibrated': 'Noch nicht kalibriert',
    'p.distance': 'Jedes Mal gleicher Abstand, etwa 30 cm',
    'p.calibrate': 'Kalibrieren',
    'p.recalibrate': 'Neu kalibrieren',
    'p.consent': 'Einwilligung',
    'p.consentOn': 'Unterschriebene Einwilligung liegt vor seit {d}',
    'p.consentMissing': 'Noch keine unterschriebene Einwilligung',
    'p.consentMark': 'Als vorliegend markieren',
    'p.consentWithdraw': 'Widerrufen',
    'p.consentHint': 'Für Aufnahmen ist die unterschriebene Einwilligung nötig. Das Formular finden Sie unter Praxis → Dokumente.',
    'p.confirmWithdraw':
      'Einwilligung von {name} widerrufen? Alle Aufnahmen von {name} werden von diesem Gerät gelöscht, und Aufnahmen sind gesperrt, bis eine neue Einwilligung vorliegt.',
    'p.deleteLink': 'Aufnahmen oder Patient löschen…',
    'p.deleteTitle': 'Löschen',
    'p.deleteAll': 'Alle Aufnahmen löschen',
    'p.deletePatient': 'Patient löschen',
    'p.confirmDeleteAll': ({ n, name }) =>
      n === 1
        ? `Die Aufnahme von ${name} löschen? Das lässt sich nicht rückgängig machen.`
        : `Alle ${n} Aufnahmen von ${name} löschen? Das lässt sich nicht rückgängig machen.`,

    'pr.pageTitle': 'Praxis · FZero',
    'pr.signed': 'Patienten haben alle nötigen Dokumente unterschrieben',
    'pr.signedHint': 'Für jeden Patienten, den Sie aufnehmen: unterschriebenes Einwilligungsformular und ausgehändigte Patienteninformation. Danach im Profil „Einwilligung liegt vor“ abhaken.',
    'pr.title': 'Praxis',
    'pr.language': 'Sprache',
    'pr.safety': 'Sicherheits-Checkliste',
    'pr.safetyHint': 'Bevor Sie FZero mit Patienten nutzen.',
    'pr.passcode': 'Dieses iPad hat einen Code',
    'pr.passcodeHint': 'Einstellungen → Face ID & Code (oder Touch ID & Code). FZero kann das nicht prüfen, bitte bestätigen Sie es.',
    'pr.confirm': 'Bestätigen',
    'pr.confirmed': 'Bestätigt',
    'pr.homescreen': 'FZero ist auf dem Home-Bildschirm',
    'pr.homescreenHint':
      'In Safari: Teilen → Zum Home-Bildschirm, dann FZero von dort öffnen. Sonst kann Safari die Daten nach 7 Tagen ohne Nutzung löschen.',
    'pr.homescreenOk': 'Vom Home-Bildschirm geöffnet',
    'pr.local': 'Patientendaten bleiben auf diesem iPad',
    'pr.localHint':
      'Nichts wird an FZero oder Dritte gesendet. In einem anderen Browser oder auf einem anderen Gerät sind keine Patienten zu sehen.',
    'pr.documents': 'Dokumente',
    'pr.docConsent': 'Einwilligungsformular für Patienten (zum Drucken)',
    'pr.docInfo': 'Patienteninformation zum Datenschutz (zum Drucken)',
    'pr.docPrivacy': 'Datenschutzerklärung dieser Website',
    'pr.docImprint': 'Impressum',
    'pr.draft': 'Entwürfe: Lassen Sie sie vor der Nutzung von Ihrer/Ihrem Datenschutzbeauftragten prüfen.',
  },
};
